from typing import Any
import os
HEADER = "# Generated by HASSL codegen\n"
def _dump_yaml(path: str, data: Any):
    try:
        import yaml
        with open(path, "w") as f:
            f.write(HEADER); yaml.safe_dump(data, f, sort_keys=False)
    except Exception:
        import json
        with open(path, "w") as f:
            f.write(HEADER); f.write(json.dumps(data, indent=2))
def ensure_dir(path: str): os.makedirs(path, exist_ok=True)
