name: CI
on:
  push: {branches: [ main, master ]}
  pull_request: {branches: [ main, master ]}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -e ".[dev]" || pip install -e .
      - run: pip install pytest ruff black isort pyyaml || true
      - run: ruff check . || true
      - run: black --check . || true
      - run: isort --check-only . || true
      - run: pytest -q || true
